import type { Calculator, CalculatorCategory } from "@/lib/calculators/types";
import type { SeoArticle, SeoCluster } from "@/lib/editorial-content";
import type { CalculatorVisualTheme } from "@/lib/calculator-visuals";
import type { AppLocale } from "@/lib/i18n";

const categoryTranslations = {
  health: {
    name: "健康",
    description: "日常健康與健身估算工具，搭配清楚公式與容易理解的說明。",
    seoTitle: "健康計算器 | BMI、熱量與健身工具",
    seoDescription: "使用免費健康計算器，快速估算 BMI、熱量、體脂與跑步配速。"
  },
  finance: {
    name: "財務",
    description: "個人財務計算器，涵蓋貸款、房貸、利息、儲蓄目標與旅遊成本。",
    seoTitle: "財務計算器 | 貸款、房貸與儲蓄工具",
    seoDescription: "使用清楚公式與範例，快速完成貸款、房貸、儲蓄與利率試算。"
  },
  math: {
    name: "數學",
    description: "適合日常比較的數學工具，包含百分比、折扣、稅額、小費與比率。",
    seoTitle: "數學計算器 | 百分比、折扣與稅額工具",
    seoDescription: "用簡單的線上工具快速解決百分比、折扣、稅額與小費問題。"
  },
  conversion: {
    name: "單位換算",
    description: "長度、重量與溫度等常用單位換算工具。",
    seoTitle: "單位換算工具 | 長度、重量與溫度",
    seoDescription: "使用簡單的線上單位換算工具，快速轉換常用單位。"
  },
  "date-time": {
    name: "日期與時間",
    description: "用於年齡、日期差與時間區間的日期時間計算工具。",
    seoTitle: "日期與時間計算器 | 年齡、時長與日期差",
    seoDescription: "用免費線上工具計算年齡、日期差與時間區間。"
  },
  "core-tools": {
    name: "核心工具",
    description: "適合日常工作的通用計算器與實用小工具。",
    seoTitle: "核心線上工具 | 計算器與實用助手",
    seoDescription: "使用適合日常工作的實用工具，處理運算式、列表、計數與快速任務。"
  },
  "transit-mobility": {
    name: "交通與移動",
    description: "旅遊、開車、油耗、騎行、距離與交通成本試算工具。",
    seoTitle: "交通與移動計算器 | 油費、計程車、汽車與自行車工具",
    seoDescription: "估算交通、駕駛、騎行、距離、油耗與車輛成本。"
  },
  "home-family": {
    name: "居家與家庭",
    description: "居家、家電、育兒、寵物、水族與家庭規劃工具。",
    seoTitle: "居家與家庭計算器 | 家庭規劃工具",
    seoDescription: "規劃家庭成本、家電用電、房間需求、家庭日期與寵物照護。"
  },
  lifestyle: {
    name: "生活",
    description: "習慣、花費、隨機選擇與個人規劃等輕量工具。",
    seoTitle: "生活計算器 | 習慣、隨機選擇與個人規劃工具",
    seoDescription: "使用簡單的生活工具，處理習慣、清單、寵物、決策與花費估算。"
  },
  "text-tools": {
    name: "文字工具",
    description: "適合統計、轉換與檢查文字內容的文字工具。",
    seoTitle: "文字工具 | 字數統計與寫作助手",
    seoDescription: "快速統計字數、字元、行數與其他文字資料。"
  },
  tech: {
    name: "科技",
    description: "螢幕、耗電、充電、媒體與裝置規劃工具。",
    seoTitle: "科技計算器 | PPI、耗電、充電與裝置工具",
    seoDescription: "估算螢幕密度、電池耗電、充電成本與各種科技數值。"
  },
  sports: {
    name: "運動",
    description: "用於運動統計與訓練估算的快速工具。",
    seoTitle: "運動計算器 | 棒球與跑步工具",
    seoDescription: "使用快速線上工具計算運動統計與訓練數值。"
  },
  "time-tools": {
    name: "時間工具",
    description: "計時器、循環、提醒與排程規劃工具。",
    seoTitle: "時間工具 | 計時器、提醒與排程計算器",
    seoDescription: "用線上時間工具規劃計時、提醒、工作循環與經過時間。"
  },
  "media-tools": {
    name: "媒體工具",
    description: "適合影音、影片、色彩與創作者流程的小工具。",
    seoTitle: "媒體工具 | 影片、色彩與創作者計算器",
    seoDescription: "使用媒體工具處理創作者流程、色彩、影片與製作規劃。"
  }
} as const;

const clusterTranslations = {
  "business-pricing-calculators": {
    name: "商業與定價",
    goal: "覆蓋高意圖的定價、毛利與獲利搜尋。",
    description: "適合在報價、上架或調價前釐清價格、利潤與損益兩平的工具。",
    useCases: ["商品或服務定價", "檢查損益兩平目標", "比較毛利、加價率與營收取捨"]
  },
  "marketing-ecommerce-calculators": {
    name: "行銷與電商",
    goal: "涵蓋廣告效率、平台費用與通路利潤相關搜尋。",
    description: "為行銷人員、電商經營者與賣家設計的 ROAS、ROI、費用與利潤工具。",
    useCases: ["檢查廣告獲利", "理解平台費用", "比較不同投放指標"]
  },
  "salary-work-calculators": {
    name: "薪資與工作",
    goal: "涵蓋薪酬、顧問費率、加班與實領薪資的常見搜尋。",
    description: "適合上班族、承攬者與自由工作者估算薪資、成本與實領目標。",
    useCases: ["時薪換算年薪", "計算加班與抽成", "設定自由接案報價與實領目標"]
  },
  "home-improvement-cost-calculators": {
    name: "居家工程與成本",
    goal: "覆蓋測量與工程成本搜尋，帶有明確商業意圖。",
    description: "在購買材料前，先估算房間、材料用量、耗損率與工程成本。",
    useCases: ["估算油漆、碎石與混凝土", "比較單位面積成本", "規劃房間與地板覆蓋面積"]
  },
  "personal-finance-calculators": {
    name: "個人財務",
    goal: "建立在貸款、房貸、儲蓄與利息上的常青財務主題。",
    description: "適合日常個人財務決策與情境試算的貸款、房貸、儲蓄與利息工具。",
    useCases: ["比較借款成本", "模擬儲蓄成長", "檢查負擔能力與未來價值"]
  }
} as const;

const visualTranslations = {
  health: {
    eyebrow: "健康與日常追蹤",
    statement: "適合健康檢查、訓練估算與日常進度追蹤的快速工具。",
    tags: ["健身", "健康", "日常追蹤"]
  },
  sports: {
    eyebrow: "運動與訓練",
    statement: "適合快速檢查表現、配速與訓練日數值，閱讀起來一目了然。",
    tags: ["配速", "數據", "訓練"]
  },
  lifestyle: {
    eyebrow: "生活規劃",
    statement: "讓習慣、日常選擇與個人規劃工具更輕快、更容易回來再用。",
    tags: ["習慣", "選擇", "個人規劃"]
  },
  "home-family": {
    eyebrow: "居家與工程規劃",
    statement: "材料、房間與家庭數字應該像工作桌面一樣直觀，而不是一整面文字牆。",
    tags: ["家庭", "工程成本", "規劃"]
  },
  "transit-mobility": {
    eyebrow: "交通與移動",
    statement: "距離、油耗與路線規劃工具應該更有方向感，而不是被文字埋住。",
    tags: ["路線", "油耗", "旅行"]
  },
  finance: {
    eyebrow: "財務與定價",
    statement: "讓粗略假設更快變成可用的付款、儲蓄與定價決策。",
    tags: ["付款", "儲蓄", "定價"]
  },
  "date-time": {
    eyebrow: "日期與時間規劃",
    statement: "日期差、時長與排程工具需要更整齊、更直接的閱讀節奏。",
    tags: ["日期", "時長", "規劃"]
  },
  "time-tools": {
    eyebrow: "時間工具",
    statement: "計時與循環工具需要快速操作、清楚狀態與可靠的視覺階層。",
    tags: ["計時", "循環", "排程"]
  },
  "text-tools": {
    eyebrow: "文字工具",
    statement: "讓寫作者與編輯有一個更精簡、更好掃描的工作介面。",
    tags: ["字數", "清理", "編輯"]
  },
  tech: {
    eyebrow: "科技裝置",
    statement: "裝置與螢幕工具應該像控制台，而不是一篇普通文章。",
    tags: ["裝置", "螢幕", "耗電"]
  },
  "media-tools": {
    eyebrow: "媒體工作流",
    statement: "創作者工具可以有氛圍，但版面階層仍要以操作性為主。",
    tags: ["創作工具", "製作", "媒體數值"]
  },
  math: {
    eyebrow: "計算與比較",
    statement: "數學工具應該精準又容易掃描，把重點拆成能立刻閱讀的區塊。",
    tags: ["公式", "比較", "日常數學"]
  },
  conversion: {
    eyebrow: "換算與轉換",
    statement: "換算工具應該更直觀，讓使用者能快速從一個單位切到下一個。",
    tags: ["單位", "精度", "快速查詢"]
  },
  "core-tools": {
    eyebrow: "核心工具",
    statement: "通用工具頁也應該有明確節奏與結構，而不是看起來很普通。",
    tags: ["工具", "速度", "重複使用"]
  }
} as const;

type ArticleTranslation = {
  title?: string;
  primaryKeyword?: string;
  contentType?: string;
  metaTitle?: string;
  metaDescription?: string;
  intro?: string;
  outline?: string[];
};

const calculatorTitleTranslations: Partial<Record<string, string>> = {
  "bmi-calculator": "BMI 計算器",
  "loan-payment-calculator": "貸款還款計算器",
  "percentage-calculator": "百分比計算器",
  "unit-price-calculator": "單價計算器",
  "compound-interest-calculator": "複利計算器",
  "mortgage-calculator": "房貸計算器",
  "tip-calculator": "小費計算器",
  "discount-calculator": "折扣計算器",
  "sales-tax-calculator": "銷售稅計算器",
  "savings-goal-calculator": "儲蓄目標計算器",
  "calorie-calculator": "熱量計算器",
  "body-fat-calculator": "體脂計算器",
  "pace-calculator": "配速計算器",
  "age-calculator": "年齡計算器",
  "date-difference-calculator": "日期差計算器",
  "time-duration-calculator": "時間區間計算器",
  "basic-calculator": "基本計算器",
  "one-line-expression-calculator": "單行算式計算器",
  "calculation-notebook": "計算筆記本",
  "engineering-calculator": "工程計算器",
  "scientific-calculator-with-history": "含歷史紀錄的科學計算器",
  "cycle-calculator": "週期計算器",
  "cycle-based-fitness-planner": "週期式健身規劃器",
  "cycle-based-wellness-planner": "週期式健康規劃器",
  "mood-check-tool": "心情檢查工具",
  "pregnancy-date-calculator": "孕期日期計算器",
  "conception-date-calculator": "受孕日期計算器",
  "baby-age-in-days-calculator": "寶寶天數計算器",
  "28-day-cycle-care-planner": "28 天週期照護規劃器",
  "public-holiday-calendar-helper": "假日行事曆助手",
  "date-add-subtract-calculator": "日期加減計算器",
  "workday-calculator": "工作天計算器",
  "day-counter": "天數計數器",
  "kids-timer": "兒童計時器",
  "currency-converter": "貨幣轉換器",
  "color-count-tool": "顏色計數工具",
  "chinese-text-utility": "中文文字工具",
  "word-count-tool": "字數統計工具",
  "random-draw-tool": "隨機抽取工具",
  "rotating-savings-bid-calculator": "輪標標金計算器",
  "stock-limit-up-limit-down-calculator": "股票漲跌停計算器",
  "stock-profit-loss-calculator": "股票損益計算器",
  "stock-ex-dividend-calculator": "股票除權息計算器",
  "buy-vs-rent-calculator": "買房與租房計算器",
  "interval-timer": "區間計時器",
  "stopwatch-session-calculator": "碼表時段計算器",
  "millisecond-stopwatch-planner": "毫秒碼表規劃器",
  "dog-pregnancy-due-date-calculator": "狗狗預產期計算器",
  "cat-pregnancy-due-date-calculator": "貓咪預產期計算器",
  "countdown-alarm-planner": "倒數鬧鐘規劃器",
  "visual-countdown-alarm-planner": "視覺倒數鬧鐘規劃器",
  "cuckoo-clock-planner": "咕咕鐘規劃器",
  "pomodoro-timer": "番茄鐘計時器",
  "youtube-alarm-planner": "YouTube 鬧鐘規劃器",
  "multi-youtube-player-planner": "多 YouTube 播放器規劃器",
  "perpetual-calendar-with-notes": "萬年曆筆記工具",
  "365-savings-plan-calculator": "365 儲蓄計畫計算器",
  "gravel-calculator": "碎石計算器",
  "paint-calculator": "油漆計算器",
  "pricing-calculator": "定價計算器",
  "overtime-calculator": "加班費計算器",
  "take-home-pay-calculator": "實領薪資計算器",
  "hidden-cash-calculator": "隱藏現金計算器"
};

const articleTranslations: Partial<Record<string, ArticleTranslation>> = {
  "how-to-calculate-profit-margin": {
    title: "如何計算產品與服務的利潤率",
    primaryKeyword: "利潤率計算器",
    contentType: "教學文章",
    metaTitle: "如何計算利潤率 + 免費利潤率計算器 | CalculatorMap",
    metaDescription: "透過範例、公式與免費計算器，學會如何計算產品與服務的利潤率。",
    intro: "這篇指南會幫你理解什麼是利潤率、比較它與加價率的差別，並用更貼近實務的營收與成本假設來檢查定價。",
    outline: ["什麼是利潤率", "毛利率、營業利潤率與淨利率", "利潤率公式", "產品與服務的實例", "常見定價錯誤", "什麼時候該看加價率", "常見問題"]
  },
  "markup-vs-margin-formula-examples": {
    title: "加價率 vs 利潤率：公式、範例與常見錯誤",
    primaryKeyword: "加價率與利潤率計算器",
    contentType: "比較文章",
    metaTitle: "加價率 vs 利潤率：公式、差異與計算器 | CalculatorMap",
    metaDescription: "用簡單公式、範例與免費計算器比較加價率與利潤率，避免常見定價錯誤。",
    intro: "加價率和利潤率關係很近，卻常常被混用。這一頁會說明兩者如何運作，以及用錯公式時，定價判斷會怎麼悄悄失真。",
    outline: ["什麼是加價率", "什麼是利潤率", "核心差異", "公式比較表", "真實商業範例", "常見錯誤", "常見問題"]
  },
  "break-even-point-explained": {
    title: "新創與小型企業的損益兩平點解說",
    primaryKeyword: "損益兩平計算器",
    contentType: "解說文章",
    metaTitle: "損益兩平點解說 + 免費損益兩平計算器 | CalculatorMap",
    metaDescription: "了解損益兩平公式、如何計算銷售單位與營收目標，並使用免費損益兩平計算器。",
    intro: "損益兩平是定價、固定成本與單位貢獻毛利終於對齊的檢查點。這篇指南會幫你在報價或上線前看懂它為什麼重要。",
    outline: ["什麼是損益兩平", "固定成本與變動成本", "損益兩平公式", "以單位計算 vs 以營收計算", "情境範例", "當利潤目標改變時", "常見問題"]
  },
  "freelance-pricing-calculator-how-much-should-you-charge": {
    title: "自由接案定價計算器：你該收多少？",
    primaryKeyword: "自由工作費率計算器",
    contentType: "情境文章",
    metaTitle: "自由工作費率計算器：設定你的時薪或專案價格 | CalculatorMap",
    metaDescription: "使用自由工作費率計算器，依收入目標、成本與可計費工時計算時薪與專案報價。",
    intro: "當你不再靠猜，而是從收入目標、營業成本、稅負和真實可計費工時出發時，自由接案定價就會清楚很多。",
    outline: ["為什麼自由接案定價很難", "時薪與專案制", "收入目標法", "可計費工時法", "成本與稅務調整", "報價範例", "常見問題"]
  },
  "hourly-to-salary-convert-your-pay": {
    title: "時薪轉年薪：按週、按月、按年換算你的收入",
    primaryKeyword: "時薪轉年薪計算器",
    contentType: "教學文章",
    metaTitle: "時薪轉年薪計算器：週薪、月薪與年薪換算 | CalculatorMap",
    metaDescription: "用公式、範例與免費計算器，把時薪換算成週薪、月薪與年薪。",
    intro: "這篇指南會帶你看標準的時薪轉年薪公式，以及加班、工時變動與無薪時間如何扭曲表面上的收入數字。",
    outline: ["基本時薪轉年薪公式", "週、月、年換算", "全職與兼職範例", "把加班算進去", "稅前與稅後收入", "常見問題"]
  },
  "commission-structures-explained": {
    title: "佣金制度解析：固定式、階梯式與營收型",
    primaryKeyword: "佣金計算器",
    contentType: "比較文章",
    metaTitle: "佣金計算器指南：固定式、階梯式與營收型 | CalculatorMap",
    metaDescription: "用公式、範例與免費計算器比較固定式、階梯式與營收型佣金制度。",
    intro: "佣金制度看起來很簡單，但一旦拿固定式、混合式與門檻式獎金來比較，差異就會很大。這篇指南會幫你看出制度如何改變激勵與總收入。",
    outline: ["什麼是佣金", "固定佣金模式", "階梯佣金模式", "營收型佣金模式", "獎金情境範例", "哪種模式適合哪種業務團隊", "常見問題"]
  },
  "roas-calculator-guide": {
    title: "ROAS 計算器指南：什麼樣的廣告報酬率算好？",
    primaryKeyword: "ROAS 計算器",
    contentType: "教學文章",
    metaTitle: "ROAS 計算器：公式、基準與範例 | CalculatorMap",
    metaDescription: "使用這個 ROAS 計算器衡量廣告報酬率、比較不同活動，並了解什麼樣的 ROAS 才算合理。",
    intro: "當你把 ROAS 放回利潤率、固定成本與通路差異裡一起看時，它才真正有意義，而不是只是單看一個比值。",
    outline: ["什麼是 ROAS", "ROAS 公式", "ROAS vs ROI", "什麼是好的 ROAS", "廣告活動計算範例", "如何改善 ROAS", "常見問題"]
  },
  "cpm-vs-cpc-vs-cpa": {
    title: "CPM、CPC、CPA：哪個指標最重要？",
    primaryKeyword: "CPM vs CPC",
    contentType: "比較文章",
    metaTitle: "CPM、CPC、CPA：差異、公式與計算器 | CalculatorMap",
    metaDescription: "用公式、範例與計算器比較 CPM、CPC 與 CPA，找出最適合你廣告活動的指標。",
    intro: "CPM、CPC 與 CPA 各自回答不同的績效問題。這篇指南會幫你挑出真正符合廣告階段的那個指標。",
    outline: ["什麼是 CPM", "什麼是 CPC", "什麼是 CPA", "什麼時候該看哪個指標", "公式範例", "常見報表錯誤", "常見問題"]
  },
  "etsy-fee-calculator-real-profit": {
    title: "Etsy 費用計算器：估算平台成本後的真實利潤",
    primaryKeyword: "Etsy 費用計算器",
    contentType: "情境文章",
    metaTitle: "Etsy 費用計算器：估算費用、運費與利潤 | CalculatorMap",
    metaDescription: "用這個 Etsy 費用計算器估算平台手續費、運費成本與真實利潤，並查看清楚的賣家拆解。",
    intro: "當平台費用、運費與廣告一起堆上來時，利潤消失得很快。這篇指南會拆解在判斷商品是否有賺之前，你該把哪些成本算進去。",
    outline: ["Etsy 主要費用說明", "運費如何影響利潤", "廣告如何改變毛利", "單一商品範例", "損益兩平售價規劃", "常見問題"]
  },
  "shopify-profit-calculator-product-cost-shipping-ad-spend": {
    title: "Shopify 利潤計算器：產品成本、運費與廣告支出",
    primaryKeyword: "Shopify 利潤計算器",
    contentType: "情境文章",
    metaTitle: "Shopify 利潤計算器：費用、運費、廣告與毛利 | CalculatorMap",
    metaDescription: "使用這個 Shopify 利潤計算器，估算扣除產品成本、支付手續費、運費與廣告支出後的毛利。",
    intro: "Shopify 利潤通常不是被一筆大費用吃掉，而是一串小成本慢慢堆出來。這一頁會幫你把整個成本結構看清楚，知道哪幾個變數最重要。",
    outline: ["Shopify 成本項目", "支付處理費用", "出貨與履約成本", "廣告支出如何影響利潤", "商店情境範例", "常見問題"]
  },
  "concrete-cost-calculator-bags-or-yards": {
    title: "混凝土成本計算器：你需要幾包或幾立方碼？",
    primaryKeyword: "混凝土成本計算器",
    contentType: "教學文章",
    metaTitle: "混凝土成本計算器：包數、立方碼與工程估算 | CalculatorMap",
    metaDescription: "用耗損係數範例與免費計算器，依包數或立方碼估算混凝土用量與工程成本。",
    intro: "先把面積和厚度換成立體體積，再去比較包數、立方碼與供應商價格，混凝土規劃就會容易很多。",
    outline: ["包數與立方碼的差別", "混凝土體積公式", "耗損係數基礎", "成本估算範例", "車道與地坪情境", "常見問題"]
  },
  "paint-calculator-by-room-size": {
    title: "依房間尺寸估算的油漆計算器：牆面、天花板與耗損係數",
    primaryKeyword: "油漆計算器",
    contentType: "教學文章",
    metaTitle: "依房間尺寸的油漆計算器：覆蓋率、塗層數與耗損 | CalculatorMap",
    metaDescription: "用免費計算器依房間尺寸、牆面面積、塗層數與耗損係數，估算你需要多少油漆。",
    intro: "當房間面積、塗層數與耗損分開估時，油漆需求很容易算錯。這篇指南會教你把它們整合成一個完整的覆蓋率檢查。",
    outline: ["房間尺寸與牆面面積", "油漆覆蓋率基礎", "塗幾層才合理", "耗損係數怎麼抓", "估算範例", "常見問題"]
  },
  "gravel-calculator-with-cost-estimate": {
    title: "附成本估算的碎石計算器：車道與景觀工程",
    primaryKeyword: "碎石計算器",
    contentType: "情境文章",
    metaTitle: "附成本估算的碎石計算器：車道與庭院工程 | CalculatorMap",
    metaDescription: "用免費計算器與範例，估算車道、步道與景觀工程的碎石體積與成本。",
    intro: "碎石工程常常敗在厚度假設、密度估法或多買太多。這篇指南會幫你把量測結果換成噸數與成本，少一點意外。",
    outline: ["碎石體積公式", "體積如何換成噸數", "深度與壓實率", "車道與步道範例", "成本估算方式", "常見問題"]
  }
};

const exactTextTranslations: Record<string, string> = {
  "how-to article": "教學文章",
  "comparison article": "比較文章",
  "scenario article": "情境文章",
  "explainer article": "解說文章",
  "Free Online Tool": "免費線上工具",
  "ROAS Calculator": "ROAS 計算器",
  "ROI Calculator": "ROI 計算器",
  "CPM Calculator": "CPM 計算器",
  "CPC Calculator": "CPC 計算器",
  "Etsy Fee Calculator": "Etsy 費用計算器",
  "Shopify Profit Calculator": "Shopify 利潤計算器",
  "Etsy Fee": "Etsy 費用",
  "Shopify Profit": "Shopify 利潤",
  Revenue: "營收",
  "Ad spend": "廣告支出",
  ROAS: "ROAS",
  "Revenue after ads": "扣除廣告後營收",
  Gain: "收益",
  Cost: "成本",
  "Net proceeds": "實收金額",
  "Net profit": "淨利",
  "Gross revenue": "總營收",
  "Platform fees": "平台費用",
  "Payment fees": "支付費用",
  Impressions: "曝光次數",
  Clicks: "點擊次數",
  "Product price": "產品售價",
  "Product cost": "產品成本",
  "Shipping charged": "向客戶收取的運費",
  "Shipping cost": "運費成本",
  "Payment fee": "支付手續費",
  Male: "男性",
  Female: "女性",
  Sedentary: "久坐",
  "Lightly active": "輕度活動",
  "Moderately active": "中度活動",
  "Very active": "高度活動",
  Annually: "每年",
  Quarterly: "每季",
  Monthly: "每月",
  Daily: "每日",
  Millimeters: "毫米",
  Centimeters: "公分",
  Meters: "公尺",
  Kilometers: "公里",
  Inches: "英吋",
  Feet: "英尺",
  Yards: "碼",
  Miles: "英里",
  Grams: "克",
  Kilograms: "公斤",
  Ounces: "盎司",
  Pounds: "磅",
  "US tons": "美噸",
  Celsius: "攝氏",
  Fahrenheit: "華氏",
  Kelvin: "開爾文",
  "This calculator uses the displayed inputs in a transparent arithmetic formula. Editable assumptions are provided where rates or rules can vary.": "這個計算器會依照畫面上的輸入，以透明的算式進行計算。當比率或規則可能依情境而變動時，也提供可編輯的假設欄位。",
  "This tool uses the inputs above to produce a practical estimate.": "這個工具會根據上方輸入，提供一個實務可用的估算結果。",
  "Enter the requested inputs.": "輸入所需資料。",
  "Keep any editable rule or rate fields aligned with your situation.": "讓可編輯的規則或比率欄位符合你的實際情況。",
  "Review the result and notes before using the estimate.": "在採用這個估算前，先檢查結果與備註。",
  "Adjust the defaults to match your scenario, then calculate the estimate.": "先把預設值調整成你的情境，再開始計算。",
  "This is an estimate for planning and should be checked against official or current rules when money, health, or legal decisions are involved.": "這是用於規劃的估算結果；若涉及金錢、健康或法律決策，請再對照官方或最新規則。",
  "The implementation is original and keeps variable rates editable where local rules may change.": "此頁採用原創實作，並保留可調整的變動比率欄位，以因應不同地區規則。",
  "Can I change the assumptions?": "我可以調整假設值嗎？",
  "Yes. Editable rate and rule fields are included when the exact rule can vary by place, provider, or date.": "可以。當實際規則會因地區、服務提供者或日期而不同時，頁面會提供可編輯的比率與規則欄位。",
  "Is this copied from another site?": "這是從別的網站複製來的嗎？",
  "No. This page uses an original implementation and rewrites the calculator structure, labels, formulas, and copy.": "不是。這一頁使用原創實作，並重新編寫了計算器結構、欄位、公式與文案。",
  "Measure return on ad spend and revenue left after ad cost.": "衡量廣告報酬率，以及扣除廣告成本後剩下的營收。",
  "Calculate return on investment from gain and cost.": "根據收益與成本計算投資報酬率。",
  "Estimate cost per thousand impressions from spend and impressions.": "根據花費與曝光次數估算每千次曝光成本。",
  "Estimate cost per click from total spend and click volume.": "根據總花費與點擊量估算每次點擊成本。",
  "Estimate marketplace fees, net proceeds, and profit for an Etsy-style order.": "估算 Etsy 類型訂單的平台費用、實收金額與利潤。",
  "Estimate ecommerce order profit after product cost, shipping, fees, and ad spend.": "估算扣除產品成本、運費、費用與廣告支出後的電商訂單利潤。",
  "This guide shows the standard hourly-to-salary conversion and the places where overtime, schedule changes, and unpaid time can distort the headline number.": "這篇指南會帶你看標準的時薪轉年薪方式，以及加班、排班變動與無薪時間會如何扭曲表面上的薪資數字。",
  "No.": "不是。",
  "Yes.": "可以。",
  "Is BMI accurate for everyone?": "BMI 對每個人都準確嗎？",
  "What formula does this calculator use?": "這個計算器使用什麼公式？",
  "BMI is a quick screening metric. It can be less useful for athletes, older adults, children, and pregnant people.": "BMI 是快速篩檢指標，但對運動員、年長者、兒童與孕婦的參考性可能較低。",
  "It uses weight in kilograms divided by height in meters squared.": "它使用體重（公斤）除以身高（公尺）的平方。",
  "Estimated body mass index.": "估算的身體質量指數。",
  "Lower end of the BMI 18.5-24.9 range in kg.": "BMI 18.5-24.9 範圍的較低體重值（公斤）。",
  "Higher end of the BMI 18.5-24.9 range in kg.": "BMI 18.5-24.9 範圍的較高體重值（公斤）。",
  "Upper end of the BMI 18.5-24.9 range in kg.": "BMI 18.5-24.9 範圍的較高體重值（公斤）。",
  "This BMI calculator estimates body mass index using a standard metric formula. It is intended for quick screening and should not replace medical advice.": "這個 BMI 計算器使用標準公制公式估算身體質量指數，適合快速篩檢，但不能取代醫療建議。",
  "Enter your height and weight to estimate BMI and a general healthy-weight range.": "輸入你的身高與體重，估算 BMI 與一般健康體重範圍。",
  "BMI = weight in kilograms / height in meters squared.": "BMI = 體重（公斤）/ 身高（公尺）的平方。",
  "Example: 70 kg and 175 cm gives BMI 22.86.": "範例：70 公斤、175 公分時，BMI 約為 22.86。",
  "BMI is a screening metric and does not account for body composition, age, or pregnancy.": "BMI 是篩檢指標，未納入身體組成、年齡或孕期差異。",
  "Estimate monthly loan payments, total payment, and total interest.": "估算每月貸款還款、總還款額與總利息。",
  "Enter a loan amount, annual interest rate, and term to estimate your monthly payment.": "輸入貸款金額、年利率與期數，估算你的每月還款。",
  "Find a percentage of a number and compare increase or decrease.": "計算某個數字的百分比，並比較增加或減少後的結果。",
  "Enter a base value and a percentage to calculate the percentage amount.": "輸入基礎數值與百分比，計算百分比金額。",
  "Compare prices by calculating cost per unit.": "用每單位成本比較不同價格。",
  "Enter the total price and quantity to find the price per unit.": "輸入總價與數量，找出每單位價格。",
  "Estimate future value and interest earned over time.": "估算未來價值與一段時間內累積的利息。",
  "Enter principal, annual rate, years, and compounding frequency to estimate future value.": "輸入本金、年利率、年數與複利頻率，估算未來價值。",
  "Estimate mortgage principal, interest, and monthly housing costs.": "估算房貸本金、利息與每月住房成本。",
  "Enter home price, down payment, rate, term, and monthly costs to estimate mortgage payments.": "輸入房價、頭期款、利率、期數與每月成本，估算房貸還款。",
  "Calculate tip amount, total bill, and split cost per person.": "計算小費金額、總帳單與每人分攤費用。",
  "Enter bill amount, tip percentage, and number of people to split the total.": "輸入帳單金額、小費比例與人數，計算每人分攤總額。",
  "Calculate sale price, discount amount, and optional tax.": "計算折後價格、折扣金額與可選稅額。",
  "Enter original price, discount percentage, and tax rate to estimate the final price.": "輸入原價、折扣比例與稅率，估算最終價格。",
  "Calculate tax amount and total price after tax.": "計算稅額與含稅總價。",
  "Enter a price and tax rate to estimate sales tax and the total after tax.": "輸入價格與稅率，估算銷售稅與含稅總額。",
  "Estimate how long it takes to reach a savings goal.": "估算達成儲蓄目標需要多久時間。",
  "Enter goal amount, current savings, and monthly contribution to estimate your timeline.": "輸入目標金額、目前存款與每月投入，估算達標時程。",
  "Estimate BMR, maintenance calories, and a simple weight-loss target.": "估算 BMR、維持熱量與簡單的減重目標。",
  "Enter body details and activity level to estimate daily calorie needs.": "輸入身體資料與活動量，估算每日熱量需求。",
  "Estimate body fat percentage using circumference measurements.": "用圍度量測值估算體脂率。",
  "Enter circumference measurements in centimeters to estimate body fat percentage.": "輸入以公分為單位的圍度量測值，估算體脂率。",
  "Calculate running pace, total minutes, and speed.": "計算跑步配速、總分鐘數與速度。",
  "Enter distance and time to calculate pace and speed.": "輸入距離與時間，計算配速與速度。",
  "Calculate age in years, months, and total months.": "計算年齡、月數與總月數。",
  "Enter a birth date and as-of date to calculate age.": "輸入出生日期與基準日期，計算年齡。",
  "Calculate days, weeks, and approximate months between two dates.": "計算兩個日期之間的天數、週數與約略月數。",
  "Enter two dates to calculate days, weeks, and approximate months between them.": "輸入兩個日期，計算它們之間的天數、週數與約略月數。",
  "Calculate elapsed time between two 24-hour times.": "計算兩個 24 小時制時間之間的經過時長。",
  "Enter start time, end time, and break minutes to calculate a time duration.": "輸入開始時間、結束時間與休息分鐘數，計算總時長。",
  "Convert between common length and distance units.": "換算常用長度與距離單位。",
  "Enter a value and choose units to convert length or distance.": "輸入數值並選擇單位，換算長度或距離。",
  "Convert between grams, kilograms, ounces, pounds, and tons.": "換算克、公斤、盎司、磅與噸。",
  "Enter a value and select units to convert weight.": "輸入數值並選擇單位，換算重量。",
  "Convert Celsius, Fahrenheit, and Kelvin.": "換算攝氏、華氏與開爾文。",
  "Enter a temperature and choose source and target units.": "輸入溫度並選擇來源與目標單位。",
  "Estimate fuel needed, trip cost, and cost per mile.": "估算所需燃料、旅程成本與每英里成本。",
  "Enter distance, fuel economy, and price per gallon to estimate fuel cost.": "輸入距離、油耗與每加侖價格，估算燃料成本。",
  "Estimate a planning date from a cycle start and an editable day offset.": "根據週期開始日期與可編輯的天數偏移，估算規劃日期。",
  "Estimate a wellness planning date from a cycle start and an editable day offset.": "根據週期開始日期與可編輯的天數偏移，估算健康規劃日期。",
  "Estimate corrected age in weeks from chronological age and weeks early.": "根據實際年齡與提早出生週數，估算以週為單位的校正年齡。",
  "Plan a 28-day cycle milestone from a start date and editable offset.": "根據開始日期與可編輯偏移，規劃 28 天週期里程碑。",
  "Cycle start date": "週期開始日期",
  "As-of date": "基準日期",
  "Chronological age": "實際年齡",
  "Corrected age": "校正年齡",
  "Weeks early": "提早出生週數"
};

const wordTranslations: Record<string, string> = {
  this: "這個",
  that: "那個",
  these: "這些",
  those: "那些",
  your: "你的",
  you: "你",
  to: "到",
  by: "透過",
  in: "以",
  it: "它",
  its: "它的",
  they: "它們",
  their: "它們的",
  them: "它們",
  yes: "可以",
  no: "不是",
  does: "有",
  do: "做",
  did: "做了",
  is: "是",
  are: "是",
  can: "可以",
  should: "應該",
  not: "不",
  only: "只",
  when: "當",
  where: "在哪裡",
  what: "什麼",
  why: "為什麼",
  which: "哪個",
  today: "今天",
  about: "大約",
  after: "之後",
  before: "之前",
  with: "搭配",
  for: "用於",
  over: "在整個期間",
  then: "然後",
  than: "比",
  across: "跨",
  include: "包含",
  included: "已包含",
  excludes: "不含",
  intended: "設計為",
  replace: "取代",
  uses: "使用",
  used: "使用",
  helpful: "有幫助",
  accurate: "準確",
  everyone: "每個人",
  general: "一般",
  standard: "標準",
  screening: "篩檢",
  metric: "指標",
  medical: "醫療",
  advice: "建議",
  composition: "組成",
  athletes: "運動員",
  older: "較年長",
  adults: "成人",
  pregnant: "懷孕",
  selected: "已選擇",
  choose: "選擇",
  choice: "選項",
  version: "版本",
  demo: "示範",
  actual: "實際",
  rough: "粗略",
  local: "本地",
  location: "地區",
  product: "產品",
  products: "產品",
  service: "服務",
  services: "服務",
  package: "包裝",
  packages: "包裝",
  grocery: "雜貨",
  bulk: "大量",
  purchases: "購買",
  alternatives: "替代選項",
  same: "相同",
  type: "類型",
  types: "類型",
  start: "開始",
  end: "結束",
  care: "照護",
  birth: "出生",
  year: "年",
  annual: "年度",
  daily: "每日",
  hours: "小時",
  hour: "小時",
  minutes: "分鐘",
  minute: "分鐘",
  duration: "時長",
  break: "休息",
  zone: "區間",
  changed: "變動",
  adjustment: "調整",
  adjustments: "調整",
  difference: "差值",
  approximate: "約略",
  planning: "規劃",
  plan: "規劃",
  timeline: "時程",
  contribution: "投入",
  contributions: "投入",
  income: "收入",
  revenue: "營收",
  gross: "毛額",
  net: "淨額",
  deductions: "扣除項目",
  insurance: "保險",
  property: "房產",
  closing: "結案",
  payment: "付款",
  payments: "付款",
  term: "期限",
  repayment: "還款",
  rules: "規則",
  rule: "規則",
  market: "市場",
  returns: "報酬",
  return: "報酬",
  basal: "基礎",
  metabolic: "代謝",
  needs: "需求",
  level: "程度",
  nutrition: "營養",
  waist: "腰圍",
  neck: "頸圍",
  hip: "臀圍",
  measurement: "量測",
  kilometers: "公里",
  miles: "英里",
  mile: "英里",
  feet: "英尺",
  foot: "英尺",
  yards: "碼",
  ton: "噸",
  tons: "噸",
  grams: "克",
  kilograms: "公斤",
  centimeters: "公分",
  meters: "公尺",
  inches: "英吋",
  pounds: "磅",
  ounces: "盎司",
  celsius: "攝氏",
  fahrenheit: "華氏",
  kelvin: "開爾文",
  traffic: "交通",
  terrain: "地形",
  driving: "駕駛",
  electric: "電動",
  vehicles: "車輛",
  force: "力",
  physically: "物理上",
  meaningful: "有意義",
  direct: "直接",
  field: "欄位",
  fields: "欄位",
  base: "基礎",
  amount: "金額",
  amounts: "金額",
  quantity: "數量",
  quantities: "數量",
  source: "來源",
  converts: "換算",
  conversion: "換算",
  conversions: "換算",
  supported: "支援",
  entered: "輸入的",
  items: "項目",
  item: "項目",
  equal: "等於",
  equals: "等於",
  plus: "加上",
  minus: "減去",
  divide: "除以",
  divided: "除以",
  multiply: "乘上",
  scale: "縮放",
  scaled: "縮放後",
  part: "部分",
  parts: "部分",
  final: "最終",
  percent: "百分比",
  saving: "儲蓄",
  saved: "已儲存",
  spending: "花費",
  challenge: "挑戰",
  budget: "預算",
  car: "汽車",
  owner: "屋主",
  renter: "租客",
  owning: "持有",
  renting: "租屋",
  session: "時段",
  friendly: "友善",
  free: "免費",
  known: "已知",
  holidays: "假日",
  workdays: "工作天",
  parked: "停車",
  cap: "上限",
  water: "水",
  hot: "熱水",
  cool: "冷水",
  mixed: "混合",
  volume: "體積",
  liters: "公升",
  milliliters: "毫升",
  cylindrical: "圓柱形",
  fluid: "液量",
  diameter: "直徑",
  drink: "飲品",
  drinks: "飲品",
  metabolism: "代謝",
  parent: "家長",
  parents: "家長",
  adult: "成人",
  heights: "身高",
  places: "位置",
  charging: "充電",
  battery: "電池",
  efficiency: "效率",
  power: "功率",
  energy: "能耗",
  usage: "用量",
  air: "空調",
  conditioner: "冷氣",
  cooling: "冷房",
  capacity: "容量",
  subject: "主體",
  sensor: "感光元件",
  circle: "圈",
  confusion: "模糊圈",
  hyperfocal: "超焦距",
  test: "測試",
  milliseconds: "毫秒",
  colors: "顏色",
  resolution: "解析度",
  diagonal: "對角線",
  pixels: "像素",
  inch: "每英吋",
  concentration: "濃度",
  taxi: "計程車",
  waiting: "等待",
  surcharge: "加成費",
  engine: "引擎",
  wheel: "輪",
  front: "前",
  rear: "後",
  teeth: "齒數",
  drive: "驅動",
  tire: "輪胎",
  aspect: "扁平比",
  rim: "輪圈",
  old: "舊",
  change: "變化",
  card: "卡片",
  home: "本地",
  destination: "目的地",
  multiplier: "乘數",
  method: "方法",
  methods: "方法",
  trade: "交易",
  broker: "券商",
  previous: "前一日",
  close: "收盤",
  dividend: "股利",
  dividends: "股利",
  group: "群組",
  members: "成員",
  pot: "標金",
  received: "已收",
  refinancing: "轉貸",
  grace: "寬限",
  period: "期間",
  accrued: "累積",
  bid: "標金",
  hits: "安打",
  batting: "打擊",
  innings: "局數",
  pitched: "投球局數",
  running: "跑步",
  sleeping: "睡眠",
  fall: "入睡",
  asleep: "睡著",
  cycles: "週期",
  sequence: "序列",
  chime: "報時",
  schedule: "排程",
  multipliers: "倍率",
  factor: "係數",
  factors: "係數",
  draft: "草稿",
  sunrise: "日出",
  sunset: "日落",
  daylight: "日照",
  real: "實際",
  promotions: "促銷",
  recommended: "建議",
  required: "所需",
  rate: "比率",
  spend: "花費",
  clicks: "點擊",
  impr: "曝光",
  listing: "刊登",
  ads: "廣告",
  offsite: "站外",
  cubic: "立方",
  bag: "袋",
  bags: "袋數",
  density: "密度",
  convert: "換算",
  electricity: "電力",
  during: "在期間",
  online: "線上",
  expected: "預期",
  already: "已經",
  details: "細節",
  moderately: "中度",
  safe: "安全",
  targets: "目標",
  personalized: "個人化",
  especially: "尤其",
  intense: "高強度",
  converting: "轉換",
  differ: "不同",
  convenient: "方便",
  precision: "精度",
  depends: "取決於",
  consistency: "一致性",
  automatically: "自動",
  overnight: "跨夜",
  currency: "貨幣",
  scheduled: "排定",
  business: "商業",
  transaction: "交易",
  starting: "起始",
  initial: "初始",
  frequency: "頻率",
  compounded: "複利計算後",
  purchase: "購買",
  stores: "商店",
  coupons: "優惠券",
  comparisons: "比較",
  resulting: "結果",
  variable: "變數",
  point: "點",
  exist: "存在",
  greater: "大於",
  logic: "邏輯",
  full: "完整",
  shown: "顯示",
  focuses: "聚焦於",
  best: "最佳",
  matches: "符合",
  see: "查看",
  divides: "分成",
  helps: "幫助",
  quickly: "快速地",
  raw: "原始",
  totals: "總額",
  increases: "增加",
  ounce: "盎司",
  pound: "磅",
  groceries: "雜貨",
  grow: "成長",
  grows: "成長",
  finds: "計算出",
  saves: "節省",
  some: "某些",
  orders: "順序",
  straight: "直接",
  becomes: "變成",
  always: "總是",
  ignored: "忽略",
  cover: "涵蓋",
  select: "選擇",
  option: "選項",
  below: "低於",
  absolute: "絕對",
  performs: "執行",
  temperatures: "溫度",
  highway: "高速公路",
  city: "城市",
  article: "文章",
  here: "這裡",
  watts: "瓦特",
  two: "兩個",
  estimated: "估算",
  optional: "可選",
  use: "使用",
  added: "加入",
  fixed: "固定",
  increasing: "逐步增加",
  zero: "零",
  gain: "增益",
  calories: "熱量",
  burned: "燃燒",
  short: "短",
  intensity: "強度",
  without: "不含",
  adjusted: "調整後",
  compounding: "複利計息",
  more: "更多",
  off: "折扣",
  sales: "銷售",
  other: "其他",
  degrees: "度",
  style: "樣式",
  work: "工作",
  early: "提早",
  heart: "心率",
  paid: "支付",
  different: "不同",
  down: "下跌",
  math: "數學",
  like: "例如",
  summarize: "整理",
  scores: "分數",
  chronological: "實際年齡",
  corrected: "校正",
  milestone: "里程碑",
  adding: "加入",
  rounding: "進位",
  training: "訓練",
  spread: "匯差",
  color: "顏色",
  affects: "影響",
  refill: "加滿",
  reciprocal: "倒數",
  limits: "限制",
  detailed: "詳細",
  into: "轉成",
  proportional: "成比例",
  step: "步進",
  counter: "計數器",
  drinking: "飲用",
  beverage: "飲料",
  wattages: "瓦數",
  voltage: "電壓",
  economics: "經濟性",
  extra: "額外",
  goals: "目標",
  gives: "得到",
  changes: "變化",
  negative: "負值",
  want: "想要",
  everyday: "日常",
  periods: "週期",
  calculated: "計算後",
  applies: "套用",
  people: "人",
  need: "需要",
  inclusive: "含稅",
  gender: "性別",
  male: "男性",
  female: "女性",
  reached: "達成",
  many: "許多",
  each: "每個",
  charges: "費用",
  pricing: "定價",
  any: "任何",
  activity: "活動量",
  deficit: "赤字",
  conditions: "情況",
  but: "但",
  finish: "完成",
  earlier: "更早",
  varying: "變動",
  evenly: "平均",
  find: "找出",
  model: "模型",
  show: "顯示",
  displays: "顯示",
  subtracting: "扣除",
  percentages: "百分比",
  decreases: "下降",
  easier: "更容易",
  inflation: "通膨",
  means: "代表",
  balance: "餘額",
  larger: "較大",
  gratuity: "小費",
  sharing: "分攤",
  tipping: "小費",
  customs: "慣例",
  taxed: "已含稅",
  assumes: "假設",
  exemption: "免稅",
  planned: "規劃",
  toward: "朝向",
  shows: "顯示",
  and: "與",
  or: "或",
  from: "從",
  between: "之間",
  per: "每",
  using: "使用",
  of: "",
  a: "",
  an: "",
  the: "",
  simple: "簡單",
  editable: "可編輯",
  assumption: "假設",
  assumptions: "假設",
  basic: "基本",
  one: "單一",
  line: "單行",
  engineering: "工程",
  scientific: "科學",
  history: "歷史紀錄",
  evaluate: "計算",
  arithmetic: "算術",
  expression: "算式",
  expressions: "算式",
  run: "執行",
  calculation: "計算",
  calculations: "計算",
  notebook: "筆記本",
  utility: "工具",
  tool: "工具",
  tools: "工具",
  planner: "規劃器",
  planners: "規劃器",
  timer: "計時器",
  interval: "區間",
  stopwatch: "碼表",
  countdown: "倒數",
  alarm: "鬧鐘",
  visual: "視覺",
  kids: "兒童",
  child: "兒童",
  chinese: "中文",
  text: "文字",
  count: "統計",
  counts: "統計",
  words: "字數",
  word: "字數",
  characters: "字元數",
  character: "字元",
  lines: "行數",
  average: "平均",
  minimum: "最小值",
  maximum: "最大值",
  value: "數值",
  values: "數值",
  converted: "換算後",
  common: "常用",
  unit: "單位",
  units: "單位",
  whole: "整數",
  decimal: "十進位",
  number: "數字",
  numbers: "數字",
  future: "未來",
  earned: "累積",
  principal: "本金",
  housing: "房屋",
  split: "分攤",
  person: "每人",
  sale: "特價",
  increase: "增加",
  decrease: "減少",
  how: "如何",
  long: "多久",
  takes: "需要",
  reach: "達到",
  current: "目前",
  remaining: "剩餘",
  target: "目標",
  body: "身體",
  mass: "質量",
  index: "指數",
  circumference: "圍度",
  measurements: "量測值",
  years: "年",
  months: "月",
  month: "月",
  weeks: "週",
  week: "週",
  days: "天",
  day: "天",
  dates: "日期",
  date: "日期",
  times: "時間",
  time: "時間",
  elapsed: "經過",
  speed: "速度",
  quick: "快速",
  range: "範圍",
  low: "下限",
  high: "上限",
  lower: "較低",
  upper: "較高",
  healthy: "健康",
  compare: "比較",
  prices: "價格",
  price: "價格",
  calculating: "計算",
  needed: "所需",
  trip: "旅程",
  fuel: "燃料",
  monthly: "每月",
  weekly: "每週",
  hourly: "每小時",
  overtime: "加班",
  regular: "一般",
  pay: "薪資",
  payout: "支付金額",
  due: "預定",
  pregnancy: "孕期",
  conception: "受孕",
  baby: "寶寶",
  cycle: "週期",
  based: "式",
  fitness: "健身",
  wellness: "健康",
  mood: "心情",
  public: "公共",
  holiday: "假日",
  calendar: "日曆",
  helper: "助手",
  add: "加上",
  subtract: "扣除",
  next: "下一個",
  workday: "工作天",
  weekdays: "平日",
  entries: "項目",
  entry: "項目",
  pick: "抽取",
  deterministic: "固定種子",
  seed: "種子",
  viewing: "觀看",
  viewingdistance: "觀看距離",
  width: "寬度",
  height: "高度",
  depth: "深度",
  square: "平方",
  size: "尺寸",
  gear: "齒比",
  travel: "旅行",
  exchange: "匯率",
  fare: "車資",
  fee: "費用",
  fees: "費用",
  stock: "股票",
  cash: "現金",
  profit: "利潤",
  loss: "損失",
  taxes: "稅額",
  tax: "稅額",
  costs: "成本",
  cost: "成本",
  notes: "筆記",
  note: "筆記",
  multiple: "多個",
  video: "影片",
  links: "連結",
  repeated: "重複",
  timed: "計時",
  attempts: "嘗試",
  human: "人類",
  humanyear: "人類年",
  equivalents: "等值",
  breeding: "交配",
  waste: "耗損",
  tile: "磁磚",
  sleep: "睡眠",
  focal: "焦距",
  aperture: "光圈",
  reaction: "反應",
  microwave: "微波",
  shipping: "運費",
  buy: "買",
  rent: "租",
  hidden: "隱藏",
  engineeringstyle: "工程式",
  constants: "常數",
  functions: "函數",
  trigonometric: "三角",
  root: "根號",
  checks: "檢查",
  active: "工作",
  rest: "休息",
  rounds: "輪",
  round: "輪",
  playlist: "播放清單",
  setup: "配置",
  gallon: "加侖",
  gallons: "加侖",
  paint: "油漆",
  gravel: "碎石",
  concrete: "混凝土",
  box: "箱",
  boxes: "箱數",
  coverage: "覆蓋量",
  project: "專案",
  area: "面積",
  slab: "板面",
  dimensions: "尺寸",
  material: "材料",
  tonnage: "噸數",
  paste: "貼上",
  pasted: "貼上",
  list: "列表",
  scratchpad: "草稿板",
  reusable: "可重複使用",
  separated: "分隔",
  commas: "逗號",
  spaces: "空格",
  new: "新的",
  offset: "偏移",
  offsets: "偏移量",
  ratio: "比例",
  ratios: "比例",
  formula: "公式",
  formulas: "公式",
  parsed: "解析",
  small: "小型",
  allow: "允許",
  operators: "運算子",
  operator: "運算子",
  parenthesis: "括號",
  parentheses: "括號",
  supports: "支援",
  support: "支援",
  function: "函數",
  adds: "加入",
  first: "先",
  avoid: "避免",
  drift: "偏移",
  timezone: "時區",
  utc: "UTC",
  equation: "方程式",
  equations: "方程式",
  estimate: "估算",
  estimates: "估算",
  track: "追蹤",
  keep: "保留",
  total: "總計",
  result: "結果",
  results: "結果",
  requested: "所需",
  aligned: "一致",
  situation: "情況",
  official: "官方",
  legal: "法律",
  money: "金錢",
  health: "健康",
  involved: "相關",
  copied: "複製",
  another: "另一個",
  site: "網站",
  original: "原創",
  structure: "結構",
  labels: "欄位標籤",
  label: "欄位標籤",
  rewrites: "重新編寫",
  transparent: "透明",
  practical: "實務",
  scenario: "情境",
  scenarios: "情境",
  realistic: "真實",
  requestedinputs: "所需資料",
  input: "輸入",
  inputs: "輸入",
  requestedinput: "所需輸入"
};

const phraseTranslations: Array<[string, string]> = [
  ["check your", "查看你的"],
  ["from height and weight", "根據身高與體重"],
  ["healthy-weight range", "健康體重範圍"],
  ["screening metric", "篩檢指標"],
  ["medical advice", "醫療建議"],
  ["body composition", "身體組成"],
  ["in kilograms", "以公斤"],
  ["in centimeters", "以公分"],
  ["in meters squared", "以公尺平方"],
  ["fixed-rate", "固定利率"],
  ["variable-rate", "浮動利率"],
  ["pre-tax", "稅前"],
  ["after-tax", "稅後"],
  ["local time zone", "本地時區"],
  ["whole calendar months", "整個曆月"],
  ["24-hour times", "24 小時制時間"],
  ["overnight span", "跨夜區間"],
  ["standard international conversion factors", "標準國際換算係數"],
  ["electric vehicles", "電動車"],
  ["child-friendly", "兒童友善"],
  ["waist-to-hip", "腰臀比"],
  ["waist-to-height", "腰高比"],
  ["non-space", "不含空格"],
  ["mixed-water", "混水"],
  ["Hong Kong", "香港"],
  ["out-the-door", "落地總價"],
  ["out--door", "落地總價"],
  ["more-save-more", "買越多省越多"],
  ["last-period", "上次月經"],
  ["day offset", "天數偏移"],
  ["human years", "人類年齡"],
  ["power bank", "行動電源"],
  ["Final drive", "終傳比"],
  ["sidewall", "胎壁"],
  ["mixed temperature", "混合溫度"],
  ["body water", "體內水分"],
  ["standard drinks", "標準杯數"],
  ["parking fee", "停車費"],
  ["free minutes", "免費分鐘"],
  ["total payment", "總還款額"],
  ["total interest", "總利息"],
  ["percentage of a number", "某個數字的百分比"],
  ["cost per unit", "每單位成本"],
  ["future value", "未來價值"],
  ["interest earned", "累積利息"],
  ["monthly housing costs", "每月住房成本"],
  ["split cost per person", "每人分攤成本"],
  ["sale price", "特價"],
  ["tax-inclusive total", "含稅總額"],
  ["healthy range low", "健康範圍下限"],
  ["healthy range high", "健康範圍上限"],
  ["maintenance calories", "維持熱量"],
  ["weight-loss target", "減重目標"],
  ["body fat percentage", "體脂率"],
  ["running pace", "跑步配速"],
  ["future value", "未來價值"],
  ["date add/subtract", "日期加減"],
  ["one-line expression", "單行算式"],
  ["scientific calculator with history", "含歷史紀錄的科學計算器"],
  ["calculation notebook", "計算筆記本"],
  ["word count", "字數統計"],
  ["color count", "顏色計數"],
  ["random draw", "隨機抽取"],
  ["public holiday", "公共假日"],
  ["buy vs. rent", "買房與租房"],
  ["dog pregnancy due date", "狗狗預產期"],
  ["cat pregnancy due date", "貓咪預產期"],
  ["countdown alarm", "倒數鬧鐘"],
  ["visual countdown alarm", "視覺倒數鬧鐘"],
  ["youtube alarm", "YouTube 鬧鐘"],
  ["multi-youtube player", "多 YouTube 播放器"],
  ["perpetual calendar with notes", "萬年曆筆記工具"],
  ["365 savings plan", "365 儲蓄計畫"],
  ["take-home pay", "實領薪資"],
  ["stock limit-up/limit-down", "股票漲跌停"],
  ["stock profit/loss", "股票損益"],
  ["stock ex-dividend", "股票除權息"],
  ["reaction test score", "反應測試分數"],
  ["return on ad spend", "廣告報酬率"],
  ["return on investment", "投資報酬率"],
  ["Etsy Fee", "Etsy 費用"],
  ["Shopify Profit", "Shopify 利潤"],
  ["Free Online Tool", "免費線上工具"],
  ["cost per thousand impressions", "每千次曝光成本"],
  ["cost per click", "每次點擊成本"],
  ["marketplace fees", "平台費用"],
  ["net proceeds", "實收金額"],
  ["ecommerce order profit", "電商訂單利潤"],
  ["product cost", "產品成本"],
  ["shipping cost", "運費成本"],
  ["shipping charged", "向客戶收取的運費"],
  ["payment fee", "支付手續費"],
  ["payment fees", "支付費用"],
  ["gross revenue", "總營收"],
  ["net profit", "淨利"],
  ["ad spend", "廣告支出"],
  ["click volume", "點擊量"],
  ["impressions", "曝光次數"],
  ["campaigns", "廣告活動"],
  ["benchmarks", "基準"],
  ["worked example", "實作範例"],
  ["worked examples", "實作範例"],
  ["revenue after ads", "扣除廣告後營收"],
  ["monthly loan payments", "每月貸款還款"],
  ["monthly payment", "每月還款"],
  ["total payment", "總還款額"],
  ["total interest", "總利息"],
  ["loan amount", "貸款金額"],
  ["annual interest rate", "年利率"],
  ["loan term", "貸款期限"],
  ["selling price", "售價"],
  ["discount amount", "折扣金額"],
  ["tax amount", "稅額"],
  ["savings goal", "儲蓄目標"],
  ["maintenance calories", "維持熱量"],
  ["weight-loss target", "減重目標"],
  ["body fat percentage", "體脂率"],
  ["running pace", "跑步配速"],
  ["screen size", "螢幕尺寸"],
  ["fuel economy", "油耗"],
  ["fuel price", "油價"],
  ["billable hours", "可計費工時"],
  ["hourly pay", "時薪"],
  ["annual salary", "年薪"],
  ["monthly salary", "月薪"],
  ["weekly pay", "週薪"],
  ["project cost", "專案成本"],
  ["waste factor", "耗損係數"],
  ["bag count", "包數"],
  ["room area", "房間面積"],
  ["wall area", "牆面面積"],
  ["coats", "塗層數"],
  ["calculator guide", "計算器指南"],
  ["seller-friendly breakdown", "賣家友善拆解"],
  ["How to Calculate", "如何計算"],
  ["Markup vs Margin", "加價率與利潤率"],
  ["Break-Even", "損益兩平"],
  ["Business & Pricing", "商業與定價"],
  ["Marketing & Ecommerce", "行銷與電商"],
  ["Salary & Work", "薪資與工作"],
  ["Home Improvement & Cost", "居家工程與成本"],
  ["Personal Finance", "個人財務"],
  ["Body Mass Index", "身體質量指數"],
  ["Loan Payment", "貸款還款"],
  ["Unit Price", "單價"],
  ["Compound Interest", "複利"],
  ["Mortgage Grace Period", "房貸寬限期"],
  ["Mortgage Refinance", "房貸轉貸"],
  ["Mortgage", "房貸"],
  ["Savings Goal", "儲蓄目標"],
  ["Weekly Savings Challenge", "每週儲蓄挑戰"],
  ["Effective Annual Rate", "有效年利率"],
  ["Credit Card Debt", "信用卡債務"],
  ["Car Purchase Budget", "購車預算"],
  ["Travel Exchange Rate", "旅行匯率"],
  ["Tax Inclusive Price", "含稅價格"],
  ["Profit Margin", "利潤率"],
  ["Real Promotion Discount", "真實促銷折扣"],
  ["Shipping Cost Comparison", "運費比較"],
  ["Hourly to Salary", "時薪轉年薪"],
  ["Take Home Pay", "實領薪資"],
  ["Freelance Rate", "自由工作費率"],
  ["Commission", "抽成"],
  ["Calorie", "熱量"],
  ["Body Fat", "體脂"],
  ["Pregnancy Weight", "孕期體重"],
  ["Premature Baby Corrected Age", "早產兒校正年齡"],
  ["Body Shape", "體型"],
  ["Target Heart Rate", "目標心率"],
  ["Exercise Calories", "運動消耗熱量"],
  ["Running Calories", "跑步熱量"],
  ["Blood Alcohol", "血液酒精濃度"],
  ["Water Intake", "飲水量"],
  ["Waist to Hip Ratio", "腰臀比"],
  ["Smoking Cost", "吸菸花費"],
  ["Child Height Prediction", "兒童身高預測"],
  ["Sleep Cycle", "睡眠週期"],
  ["Date Difference", "日期差"],
  ["Time Duration", "時間區間"],
  ["Insurance Age", "保險年齡"],
  ["Sunrise Sunset Daylight", "日出日落與日照"],
  ["Number Base", "進位"],
  ["Shoe Size", "鞋碼"],
  ["Length", "長度"],
  ["Weight", "重量"],
  ["Temperature", "溫度"],
  ["Fuel Cost", "燃料成本"],
  ["PPM Concentration", "PPM 濃度"],
  ["Taiwan Taxi Fare", "台灣計程車車資"],
  ["Hong Kong Taxi Fare", "香港計程車車資"],
  ["Time Speed Distance", "時間速度距離"],
  ["Gear Ratio RPM", "齒比與轉速"],
  ["Tire Size Upgrade", "輪胎升級尺寸"],
  ["Fuel Price Change", "油價變動"],
  ["Bicycle Gear", "自行車齒比"],
  ["Map Distance", "地圖距離"],
  ["Parking Fee", "停車費"],
  ["Baby Formula Temperature", "奶粉溫度"],
  ["TV Viewing Distance", "電視觀看距離"],
  ["Electricity Bill", "電費"],
  ["Air Conditioner BTU", "冷氣 BTU"],
  ["Air Conditioner Electricity Cost", "冷氣耗電成本"],
  ["Aquarium Volume", "水族箱體積"],
  ["Cup Volume", "杯子容量"],
  ["Microwave Heating Time", "微波加熱時間"],
  ["Tile Area", "磁磚面積"],
  ["Concrete Cost", "混凝土成本"],
  ["Square Footage", "面積"],
  ["Flooring", "地板"],
  ["Dog Age", "狗狗年齡"],
  ["Cat Age", "貓咪年齡"],
  ["Alcohol Spending", "飲酒花費"],
  ["Reaction Test Score", "反應測試分數"],
  ["Height Match", "身高配對"],
  ["Screen PPI", "螢幕 PPI"],
  ["Electric Vehicle Charging Cost", "電動車充電成本"],
  ["Power Bank Wh", "行動電源 Wh"],
  ["Camera Distance", "相機距離"],
  ["Depth of Field", "景深"],
  ["Baseball Batting Average", "棒球打擊率"],
  ["Baseball ERA", "棒球防禦率"],
  ["Golden Ratio", "黃金比例"],
  ["Tally Counter", "計數器"],
  ["Percentage", "百分比"],
  ["Discount", "折扣"],
  ["Sales Tax", "銷售稅"],
  ["Tip", "小費"],
  ["Pace", "配速"],
  ["Age", "年齡"],
  ["Ratio", "比例"],
  ["Calculator", "計算器"],
  ["Converter", "轉換器"],
  ["Guides", "指南"],
  ["Guide", "指南"],
  ["Examples", "範例"],
  ["Example", "範例"],
  ["Formula", "公式"],
  ["profit margin", "利潤率"],
  ["break-even", "損益兩平"],
  ["markup", "加價率"],
  ["margin", "利潤率"],
  ["loan", "貸款"],
  ["mortgage", "房貸"],
  ["savings", "儲蓄"],
  ["salary", "薪資"],
  ["price", "價格"],
  ["cost", "成本"],
  ["rate", "比率"],
  ["distance", "距離"],
  ["time", "時間"],
  ["date", "日期"],
  ["height", "身高"],
  ["weight", "體重"],
  ["tax", "稅額"],
  ["bill", "帳單"],
  ["payment", "付款"],
  ["interest", "利息"],
  ["total", "總計"],
  ["goal", "目標"],
  ["amount", "金額"],
  ["hours", "小時"],
  ["months", "月"],
  ["days", "天"],
  ["result", "結果"],
  ["use cases", "使用情境"],
  ["Calculate", "計算"],
  ["calculate", "計算"],
  ["Estimate", "估算"],
  ["estimate", "估算"],
  ["Browse", "瀏覽"],
  ["Read", "閱讀"],
  ["Open", "開啟"],
  ["Start", "開始"],
  ["Enter", "輸入"],
  ["Review", "檢查"],
  ["This calculator", "這個計算器"],
  ["This tool", "這個工具"],
  ["This page", "此頁面"],
  ["Related", "相關"],
  ["Primary", "主要"],
  ["FAQ", "常見問題"]
];

const sortedPhraseTranslations = [...phraseTranslations].sort((left, right) => right[0].length - left[0].length);
const sortedWordTranslations = Object.entries(wordTranslations).sort((left, right) => right[0].length - left[0].length);

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function buildPhrasePattern(source: string) {
  const escaped = source
    .trim()
    .split(/\s+/)
    .map((part) => escapeRegExp(part))
    .join("\\s+");
  const useWordBoundary = /^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$/.test(source);

  return new RegExp(useWordBoundary ? `\\b${escaped}\\b` : escaped, "gi");
}

const compiledPhraseTranslations = sortedPhraseTranslations.map(([source, target]) => [buildPhrasePattern(source), target] as const);
const compiledWordTranslations = sortedWordTranslations.map(([source, target]) => [new RegExp(`\\b${escapeRegExp(source)}\\b`, "gi"), target] as const);

function replacePhrases(text: string) {
  return compiledPhraseTranslations.reduce((current, [pattern, target]) => current.replace(pattern, target), text);
}

function replaceWords(text: string) {
  return compiledWordTranslations.reduce((current, [pattern, target]) => current.replace(pattern, target), text);
}

function cleanupTranslatedText(text: string) {
  return text
    .replace(/\s{2,}/g, " ")
    .replace(/\s+([,.;:!?])/g, "$1")
    .replace(/([\u4e00-\u9fff])\s+([\u4e00-\u9fff])/g, "$1$2")
    .trim();
}

function translateFragment(text: string) {
  const exact = exactTextTranslations[text];
  const exactWithPeriod = exactTextTranslations[`${text}.`];

  if (exact) {
    return exact.replace(/\s+/g, " ").trim();
  }

  if (exactWithPeriod) {
    return exactWithPeriod.replace(/[。.]$/, "").replace(/\s+/g, " ").trim();
  }

  return cleanupTranslatedText(replaceWords(replacePhrases(text)));
}

function translateSentencePatterns(text: string) {
  const exact = exactTextTranslations[text];

  if (exact) {
    return exact;
  }

  const replacements: Array<[RegExp, (...values: string[]) => string]> = [
    [/^Example:\s*(.+)$/i, (value) => `範例：${translateFragment(value)}。`],
    [/^(.+)\. The implementation is original and keeps variable rates editable where local rules may change\.$/i, (summary) => `${translateFragment(summary)} 此頁採用原創實作，並保留可調整的變動比率欄位，以因應不同地區規則。`],
    [/^Enter your (.+)\.$/i, (value) => `輸入你的${translateFragment(value)}。`],
    [/^Enter the (.+)\.$/i, (value) => `輸入${translateFragment(value)}。`],
    [/^Add the (.+)\.$/i, (value) => `加入${translateFragment(value)}。`],
    [/^Choose the (.+)\.$/i, (value) => `選擇${translateFragment(value)}。`],
    [/^Choose (.+)\.$/i, (value) => `選擇${translateFragment(value)}。`],
    [/^Does this (.+)\?$/i, (value) => `這有包含${translateFragment(value)}嗎？`],
    [/^Can I use (.+)\?$/i, (value) => `我可以使用${translateFragment(value)}嗎？`],
    [/^What does (.+) mean\?$/i, (value) => `${translateFragment(value)}是什麼意思？`],
    [/^Why (.+)\?$/i, (value) => `為什麼${translateFragment(value)}？`],
    [/^What ton does this use\?$/i, () => "這裡使用的是哪一種噸？"],
    [/^Review the (.+)\.$/i, (value) => `查看${translateFragment(value)}。`],
    [/^Review (.+)\.$/i, (value) => `查看${translateFragment(value)}。`],
    [/^Use the (.+)\.$/i, (value) => `使用${translateFragment(value)}。`],
    [/^Use (.+)\.$/i, (value) => `使用${translateFragment(value)}。`],
    [/^Convert (.+)\.$/i, (value) => `換算${translateFragment(value)}。`],
    [/^Evaluate (.+)\.$/i, (value) => `計算${translateFragment(value)}。`],
    [/^Paste (.+)\.$/i, (value) => `貼上${translateFragment(value)}。`],
    [/^Track (.+)\.$/i, (value) => `追蹤${translateFragment(value)}。`],
    [/^Calculate (.+) from (.+)\.$/i, (target, source) => `根據${translateFragment(source)}計算${translateFragment(target)}。`],
    [/^Estimate (.+) from (.+)\.$/i, (target, source) => `根據${translateFragment(source)}估算${translateFragment(target)}。`],
    [/^Estimate (.+)\.$/i, (value) => `估算${translateFragment(value)}。`],
    [/^Calculate (.+)\.$/i, (value) => `計算${translateFragment(value)}。`],
    [/^Compare (.+)\.$/i, (value) => `比較${translateFragment(value)}。`],
    [/^Find (.+)\.$/i, (value) => `找出${translateFragment(value)}。`],
    [/^Scale (.+)\.$/i, (value) => `依比例換算${translateFragment(value)}。`],
    [/^Add up (.+)\.$/i, (value) => `加總${translateFragment(value)}。`],
    [/^Summarize (.+)\.$/i, (value) => `整理${translateFragment(value)}。`],
    [/^(.+) is one of the key ideas behind (.+)\. This section of (.+) explains what to check before you rely on the final number\.$/i, (heading, keyword) => `${translateFragment(heading)}是${translateFragment(keyword)}背後的核心觀念之一。這一段會說明，在你採信最終數字之前，該先檢查哪些重點。`],
    [/^Start with the related calculator, test one realistic scenario, and then use the rest of the guide to understand where the formula helps and where your assumptions matter most\.$/i, () => "先從相關計算器開始，代入一個真實情境，再用後續內容理解公式在哪些地方有幫助，以及哪些假設最需要你自己判斷。"],
    [/^Once the concept is clear, use the (.+) page on CalculatorMap to compare different inputs and pressure-test your estimate\.$/i, (pageName) => `理解概念後，再用 CalculatorMap 上的${translateFragment(pageName)}頁面比較不同輸入，進一步壓力測試你的估算。`],
    [/^What is the easiest way to work through (.+)\?$/i, (keyword) => `處理${translateFragment(keyword)}最快的方法是什麼？`],
    [/^What mistakes should I avoid with (.+)\?$/i, (keyword) => `使用${translateFragment(keyword)}時該避免哪些錯誤？`],
    [/^Which other calculators should I compare with (.+)\?$/i, (keyword) => `在${translateFragment(keyword)}之外，還該搭配哪些計算器一起看？`],
    [/^The fastest way is to open the related calculator, enter your numbers, and then use this guide to validate the formula, units, and decision points behind the result\.$/i, () => "最快的方法是先打開相關計算器、輸入你的數字，再用這篇指南確認結果背後的公式、單位與判斷重點。"],
    [/^The most common mistakes are mixing units, leaving out fees or overhead, and assuming one example applies to every scenario\. Recheck your assumptions before using the number in a real decision\.$/i, () => "最常見的錯誤包括混用單位、漏掉費用或間接成本，以及把單一範例套用到所有情況。把數字用進真實決策前，請再檢查一次你的假設。"],
    [/^Use the related calculators on this page to compare supporting variables, margins, costs, taxes, or scenario-based tradeoffs before making a decision\.$/i, () => "在做決策前，先搭配這一頁的相關計算器，比較支援變數、毛利、成本、稅額與不同情境之間的取捨。"]
  ];

  for (const [pattern, formatter] of replacements) {
    const match = text.match(pattern);

    if (match) {
      return formatter(...match.slice(1));
    }
  }

  return cleanupTranslatedText(replaceWords(replacePhrases(text)));
}

function maybeTranslate(text: string, locale: AppLocale) {
  if (locale === "en") {
    return text;
  }

  return translateSentencePatterns(text);
}

export function localizeCategory(category: CalculatorCategory, locale: AppLocale): CalculatorCategory {
  if (locale === "en") {
    return category;
  }

  const translated = categoryTranslations[category.slug as keyof typeof categoryTranslations];

  if (!translated) {
    return {
      ...category,
      name: maybeTranslate(category.name, locale),
      description: maybeTranslate(category.description, locale),
      seoTitle: maybeTranslate(category.seoTitle, locale),
      seoDescription: maybeTranslate(category.seoDescription, locale)
    };
  }

  return {
    ...category,
    name: translated.name,
    description: translated.description,
    seoTitle: translated.seoTitle,
    seoDescription: translated.seoDescription
  };
}

export function localizeCluster(cluster: SeoCluster, locale: AppLocale): SeoCluster {
  if (locale === "en") {
    return cluster;
  }

  const translated = clusterTranslations[cluster.slug as keyof typeof clusterTranslations];

  return {
    ...cluster,
    name: translated?.name ?? maybeTranslate(cluster.name, locale),
    goal: translated?.goal ?? maybeTranslate(cluster.goal, locale),
    description: translated?.description ?? maybeTranslate(cluster.description, locale),
    useCases: translated?.useCases ? [...translated.useCases] : cluster.useCases.map((item) => maybeTranslate(item, locale))
  };
}

export function localizeArticle(article: SeoArticle, locale: AppLocale): SeoArticle {
  if (locale === "en") {
    return article;
  }

  const translated = articleTranslations[article.slug];

  return {
    ...article,
    title: translated?.title ?? maybeTranslate(article.title, locale),
    primaryKeyword: translated?.primaryKeyword ?? maybeTranslate(article.primaryKeyword, locale),
    contentType: translated?.contentType ?? maybeTranslate(article.contentType, locale),
    metaTitle: translated?.metaTitle ?? maybeTranslate(article.metaTitle, locale),
    metaDescription: translated?.metaDescription ?? maybeTranslate(article.metaDescription, locale),
    intro: translated?.intro ?? maybeTranslate(article.intro, locale),
    outline: translated?.outline ? [...translated.outline] : article.outline.map((item) => maybeTranslate(item, locale)),
    sections: article.sections.map((section) => ({
      heading: maybeTranslate(section.heading, locale),
      body: section.body.map((paragraph) => maybeTranslate(paragraph, locale))
    })),
    faqs: article.faqs.map((faq) => ({
      question: maybeTranslate(faq.question, locale),
      answer: maybeTranslate(faq.answer, locale)
    }))
  };
}

export function localizeCalculator(calculator: Calculator, locale: AppLocale): Calculator {
  if (locale === "en") {
    return calculator;
  }

  const translatedTitle = calculatorTitleTranslations[calculator.slug];
  const translatedName = translatedTitle ?? maybeTranslate(calculator.name, locale);

  return {
    ...calculator,
    name: translatedName,
    h1: translatedTitle ?? maybeTranslate(calculator.h1, locale),
    shortDescription: maybeTranslate(calculator.shortDescription, locale),
    longDescription: maybeTranslate(calculator.longDescription, locale),
    intro: maybeTranslate(calculator.intro, locale),
    howToUse: calculator.howToUse.map((item) => maybeTranslate(item, locale)),
    formulaExplanation: maybeTranslate(calculator.formulaExplanation, locale),
    examples: calculator.examples.map((item) => maybeTranslate(item, locale)),
    notes: calculator.notes.map((item) => maybeTranslate(item, locale)),
    fields: calculator.fields.map((field) => ({
      ...field,
      label: maybeTranslate(field.label, locale),
      placeholder: field.placeholder ? maybeTranslate(field.placeholder, locale) : field.placeholder,
      unit: field.unit ? maybeTranslate(field.unit, locale) : field.unit,
      helpText: field.helpText ? maybeTranslate(field.helpText, locale) : field.helpText,
      options: field.options?.map((option) => ({
        ...option,
        label: maybeTranslate(option.label, locale)
      }))
    })),
    results: calculator.results.map((result) => ({
      ...result,
      label: maybeTranslate(result.label, locale),
      description: result.description ? maybeTranslate(result.description, locale) : result.description
    })),
    faqs: calculator.faqs.map((faq) => ({
      question: maybeTranslate(faq.question, locale),
      answer: maybeTranslate(faq.answer, locale)
    })),
    seo: {
      ...calculator.seo,
      title: calculator.seo.title === `${calculator.name} - Free Online Tool` && translatedTitle
        ? `${translatedTitle} - 免費線上工具`
        : maybeTranslate(calculator.seo.title, locale),
      description: maybeTranslate(calculator.seo.description, locale)
    }
  };
}

export function localizeVisualTheme(visual: CalculatorVisualTheme, categorySlug: string | undefined, locale: AppLocale): CalculatorVisualTheme {
  if (locale === "en") {
    return visual;
  }

  const translated = categorySlug ? visualTranslations[categorySlug as keyof typeof visualTranslations] : null;

  return {
    ...visual,
    eyebrow: translated?.eyebrow ?? maybeTranslate(visual.eyebrow, locale),
    statement: translated?.statement ?? maybeTranslate(visual.statement, locale),
    tags: translated?.tags ? [...translated.tags] : visual.tags.map((tag) => maybeTranslate(tag, locale))
  };
}

export function translateCalculatorError(error: string, locale: AppLocale) {
  return locale === "en" ? error : maybeTranslate(error, locale);
}
